
notifications:
  email:
    on_success: change
    on_failure: always

language: swift

stages:
  - Tests
  - Compatibility

jobs:
  include:
    - stage: Tests
      os: linux
      dist: trusty
      name: Linux Tests
      script: swift test
    - stage: Tests
      os: osx
      osx_image: xcode10.2
      name: macOS Tests
      script: swift test
